'use client'
import { useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'motion/react'

type Product={id:string,name:string,description:string|null,priceCents:number}
type Cart=Record<string,number>
const categories=['Todos','Mais pedidos','Combos','Bebidas','Sobremesas']
const money=(cents:number)=>`R$ ${(cents/100).toFixed(2).replace('.',',')}`

export default function MenuClient({shop,products}:{shop:{name:string;slug:string};products:Product[]}){
 const [cart,setCart]=useState<Cart>({}); const [query,setQuery]=useState(''); const [category,setCategory]=useState('Todos'); const [selected,setSelected]=useState<Product|null>(null); const [cartOpen,setCartOpen]=useState(false)
 const visible=useMemo(()=>products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()) && (category==='Todos'||category==='Mais pedidos'||(category==='Combos'&&p.name.toLowerCase().includes('combo'))||(category==='Bebidas'&&p.name.toLowerCase().includes('bebida'))||(category==='Sobremesas'&&/sorvete|milkshake|doce/i.test(p.name)))),[products,query,category])
 const total=products.reduce((sum,p)=>sum+(cart[p.id]||0)*p.priceCents,0); const count=Object.values(cart).reduce((a,b)=>a+b,0)
 const update=(id:string,delta:number)=>setCart(prev=>({...prev,[id]:Math.max(0,(prev[id]||0)+delta)}))
 return <main className="menu-shell"><header className="menu-header"><div><a href="/" className="menu-back">← VendaFácil</a><p className="kicker"><i/> aberto agora · pedidos online</p><h1>{shop.name}</h1><p>feito na hora, do nosso jeito.</p></div><div className="menu-badge">VF<small>cardápio<br/>digital</small></div></header>
  <div className="menu-controls"><label className="search-box"><span aria-hidden="true">⌕</span><span className="sr-only">Buscar no cardápio</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar no cardápio" /></label><button className="button button-dark" onClick={()=>setCartOpen(true)} aria-label={`Abrir carrinho com ${count} itens`}>Carrinho {count>0?`· ${count}`:''}</button></div>
  <nav className="menu-toolbar" aria-label="Categorias">{categories.map(item=><button key={item} className={category===item?'active':''} onClick={()=>setCategory(item)}>{item}</button>)}</nav>
  {visible.length===0?<div className="empty-menu"><strong>Nada encontrado por aqui.</strong><p>Tente outra busca ou volte para “Todos” para ver o cardápio completo.</p><button className="button button-dark" onClick={()=>{setQuery('');setCategory('Todos')}}>Limpar filtros</button></div>:<section className="menu-grid" aria-label="Itens do cardápio">{visible.map((p,i)=><article className="menu-product" key={p.id}><button className={`product-art art-${i%3}`} onClick={()=>setSelected(p)} aria-label={`Ver detalhes de ${p.name}`}>VF</button><div className="menu-product-body"><div><h2>{p.name}</h2><p>{p.description||'Uma escolha especial da casa.'}</p></div><footer><strong className="price">{money(p.priceCents)}</strong><button className="add-button" onClick={()=>update(p.id,1)} aria-label={`Adicionar ${p.name}`}>+</button></footer></div></article>)}</section>}
  <AnimatePresence>{selected&&<><motion.div className="drawer-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setSelected(null)} /><motion.aside className="drawer" role="dialog" aria-modal="true" aria-label={`Detalhes de ${selected.name}`} initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'spring',stiffness:320,damping:30}}><div className="drawer-header"><span className="kicker">detalhe do item</span><button className="drawer-close" onClick={()=>setSelected(null)} aria-label="Fechar">×</button></div><div className="product-art art-0" style={{minHeight:180}}>VF</div><h2>{selected.name}</h2><p>{selected.description||'Uma escolha especial da casa, preparada com cuidado.'}</p><strong className="price">{money(selected.priceCents)}</strong><button className="button button-orange drawer-action" onClick={()=>{update(selected.id,1);setSelected(null)}}>Adicionar ao carrinho</button></motion.aside></>}</AnimatePresence>
  <AnimatePresence>{cartOpen&&<><motion.div className="drawer-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setCartOpen(false)}/><motion.aside className="drawer" role="dialog" aria-modal="true" aria-label="Carrinho" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'spring',stiffness:320,damping:30}}><div className="drawer-header"><span className="kicker">seu pedido</span><button className="drawer-close" onClick={()=>setCartOpen(false)} aria-label="Fechar carrinho">×</button></div><h2>Carrinho</h2>{count===0?<div className="empty-menu"><strong>Seu carrinho está vazio.</strong><p>Adicione um item para começar seu pedido.</p></div>:<>{products.filter(p=>cart[p.id]).map(p=><div className="cart-line" key={p.id}><div><strong>{p.name}</strong><p>{money(p.priceCents)} cada</p></div><div className="quantity"><button onClick={()=>update(p.id,-1)} aria-label="Diminuir">−</button><span>{cart[p.id]}</span><button onClick={()=>update(p.id,1)} aria-label="Aumentar">+</button></div></div>)}<div className="drawer-total"><span>Total</span><span>{money(total)}</span></div><button className="button button-orange drawer-action" onClick={()=>alert('Checkout simulado: conecte aqui o fluxo de pedidos existente.')}>Continuar pedido</button><p className="demo-label">checkout ainda simulado nesta etapa</p></>}</motion.aside></>}</AnimatePresence>
  {count>0&&!cartOpen&&<div className="floating-cart"><span>{count} {count===1?'item':'itens'}</span><b>{money(total)}</b><button onClick={()=>setCartOpen(true)}>ver carrinho →</button></div>}
 </main>
}
