'use client'
import Link from 'next/link'
import { useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'motion/react'

type Order={id:string;name:string;items:string;total:string;time:string;lane:'novos'|'preparo'|'prontos'}
const seed:Order[]=[{id:'#1048',name:'Marina Costa',items:'2x Açaí 500ml',total:'R$ 37,80',time:'há 2 min',lane:'novos'},{id:'#1046',name:'João Pedro',items:'1x Sorvete 2 bolas',total:'R$ 14,00',time:'há 8 min',lane:'preparo'},{id:'#1045',name:'Bia Santos',items:'1x Açaí 500ml + adicional',total:'R$ 22,90',time:'há 12 min',lane:'preparo'},{id:'#1042',name:'Lucas Almeida',items:'3x Açaí 500ml',total:'R$ 56,70',time:'há 18 min',lane:'prontos'}]
const nextLane=(lane:Order['lane']):Order['lane']=>lane==='novos'?'preparo':lane==='preparo'?'prontos':'prontos'

export default function Admin(){
 const [orders,setOrders]=useState(seed); const [selected,setSelected]=useState<Order|null>(null); const [filter,setFilter]=useState('todos'); const [shopId]=useState('demo-shop'); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false)
 const filtered=useMemo(()=>filter==='todos'?orders:orders.filter(o=>o.lane===filter),[orders,filter])
 async function addProduct(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMessage('');const data=Object.fromEntries(new FormData(e.currentTarget));try{const res=await fetch('/api/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,shopId,priceCents:Number(data.priceCents)})});setMessage(res.ok?'Produto publicado no cardápio.':'Não foi possível criar o produto.');if(res.ok)e.currentTarget.reset()}catch{setMessage('API indisponível: produto não publicado.')}finally{setLoading(false)}}
 function advance(order:Order){setOrders(all=>all.map(item=>item.id===order.id?{...item,lane:nextLane(item.lane)}:item));setSelected(null)}
 const lanes:[Order['lane'],string][]=[['novos','Novos'],['preparo','Em preparo'],['prontos','Prontos']]
 return <main className="admin-shell"><nav className="admin-nav"><Link href="/" className="brand"><span className="brand-mark">VF</span> Venda<em>Fácil</em></Link><div className="admin-nav-links"><button className="active">Visão geral</button><button onClick={()=>setFilter('todos')}>Pedidos</button><button onClick={()=>document.getElementById('cardapio')?.scrollIntoView()}>Cardápio</button><button>Clientes</button></div><Link className="nav-login" href="/menu/demo">Ver loja ↗</Link></nav>
  <div className="admin-heading"><div><p className="kicker"><i/> quarta-feira, 09 de outubro</p><h1>Bom dia, lojista.</h1><p>Aqui está o pulso da sua operação hoje.</p><span className="demo-label">dados de demonstração — conecte sua operação para métricas reais</span></div><span className="status-pill">● loja aberta</span></div>
  <section className="metrics"><div className="metric"><small>vendas hoje · demo</small><strong>R$ 486,40</strong><span>↑ 12,5% vs. ontem</span></div><div className="metric"><small>pedidos recebidos · demo</small><strong>28</strong><span>↑ 4 pedidos</span></div><div className="metric"><small>ticket médio · demo</small><strong>R$ 17,37</strong><span>↑ 8,2% este mês</span></div><div className="metric"><small>tempo de preparo · demo</small><strong>18 min</strong><span>↓ 3 min vs. média</span></div></section>
  <div className="ops-grid"><section className="dash-panel"><div className="panel-heading"><div><h2>Pedidos em andamento</h2><p className="demo-label">fila local simulada</p></div><div className="filter-row">{['todos','novos','preparo','prontos'].map(item=><button key={item} className={filter===item?'active':''} onClick={()=>setFilter(item)}>{item==='todos'?'Todos':item}</button>)}</div></div><div className="kanban">{lanes.map(([lane,label])=><div key={lane}><div className="lane-title">{label} · {filtered.filter(o=>o.lane===lane).length}</div>{filtered.filter(o=>o.lane===lane).map(order=><motion.article layout className="order-card" key={order.id}><header><b>{order.id}</b><span>{order.time}</span></header><strong>{order.name}</strong><p>{order.items}<br/>{order.total}</p><button onClick={()=>setSelected(order)}>{lane==='prontos'?'Ver detalhes':'Atualizar pedido'}</button></motion.article>)}</div>)}</div></section>
   <aside className="dash-panel"><div className="panel-heading"><h2>Ritmo da loja</h2><span className="demo-label">demo</span></div><div className="feed"><div className="feed-item"><i className="feed-dot"/><div><strong>Pedido #1048 recebido</strong><small>agora · nova ação disponível</small></div></div><div className="feed-item"><i className="feed-dot"/><div><strong>Horário de pico se aproxima</strong><small>12h–13h · reforçar preparo</small></div></div><div className="feed-item"><i className="feed-dot"/><div><strong>Cardápio online</strong><small>última sincronização simulada</small></div></div></div></aside>
  </div>
  <section className="dash-panel" id="cardapio" style={{marginTop:14}}><div className="panel-heading"><div><h2>Publicar item no cardápio</h2><p>Esta ação usa a API de produtos existente.</p></div></div><form className="product-form" onSubmit={addProduct}><label>Nome<input name="name" required placeholder="Ex.: Combo da casa" /></label><label>Descrição<input name="description" placeholder="O que vem neste item?" /></label><label>Preço em centavos<input name="priceCents" required type="number" min="1" placeholder="1890" /></label><button className="button button-orange" disabled={loading}>{loading?'Publicando…':'Publicar item'}</button>{message&&<p className="form-message" role="status">{message}</p>}</form></section>
  <AnimatePresence>{selected&&<><motion.div className="drawer-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setSelected(null)}/><motion.aside className="admin-drawer" role="dialog" aria-modal="true"><button className="drawer-close" onClick={()=>setSelected(null)} aria-label="Fechar detalhe">×</button><p className="kicker">detalhe do pedido</p><h2>{selected.id}</h2><p>{selected.time} · fila {selected.lane}</p><h3>{selected.name}</h3><p>{selected.items}</p><strong>{selected.total}</strong><button className="button button-orange drawer-action" onClick={()=>advance(selected)}>{selected.lane==='prontos'?'Pedido concluído':'Mover para '+(selected.lane==='novos'?'preparo':'prontos')}</button><p className="demo-label">mudança de status simulada localmente</p></motion.aside></>}</AnimatePresence>
  {message&&<div className="toast" role="status">{message}</div>}
 </main>
}